"""add league description is_official prize fields

Revision ID: 3b9a38a9ed0c
Revises: 
Create Date: 2026-06-06 12:28:45.887198

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b9a38a9ed0c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leagues', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('is_official', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('prize', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leagues', schema=None) as batch_op:
        batch_op.drop_column('prize')
        batch_op.drop_column('is_official')
        batch_op.drop_column('description')

    # ### end Alembic commands ###
