"""add total_points_all_time to users

Revision ID: 4fee0f8e6980
Revises: 7f2730bfcd9f
Create Date: 2026-06-07 10:07:33.122133

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4fee0f8e6980'
down_revision = '7f2730bfcd9f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_points_all_time', sa.Integer(), nullable=False, server_default='0'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('total_points_all_time')

    # ### end Alembic commands ###
