"""feat: v2 schema - seasons competitions jornadas predictions_v2 duelos division_members

Revision ID: 59bb97d507d2
Revises: c9d5e2f1a3b6
Create Date: 2026-07-09 21:40:33.229165

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59bb97d507d2'
down_revision = 'c9d5e2f1a3b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('matches', schema=None) as batch_op:
        batch_op.add_column(sa.Column('competition_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('importance_score', sa.Float(), nullable=True))
        batch_op.create_foreign_key(None, 'competitions', ['competition_id'], ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_division', sa.Integer(), nullable=False, server_default='1'))
        batch_op.add_column(sa.Column('current_league_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'leagues', ['current_league_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('current_league_id')
        batch_op.drop_column('current_division')

    with op.batch_alter_table('matches', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('importance_score')
        batch_op.drop_column('competition_id')

    # ### end Alembic commands ###
